CREATE TYPE point_types AS ENUM (
    'point',
    'socket'
);
COMMENT ON TYPE point_types IS 'Типы точек на карте';

CREATE TABLE map_points (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    coordinates double precision[] NOT NULL,
    type point_types DEFAULT 'point'::point_types NOT NULL,
    flag_is_meeting boolean DEFAULT false NOT NULL,
    flag_has_socket boolean DEFAULT false NOT NULL,
    flag_disabled boolean DEFAULT false NOT NULL,
    description text,
    CONSTRAINT map_points_title_check CHECK ((char_length(trim(BOTH FROM title)) > 3) AND (char_length(trim(BOTH FROM title)) < 100)),
    CONSTRAINT map_points_coordinates_check CHECK (
        array_length(coordinates, 1) = 2
        AND coordinates[1] BETWEEN -180::double precision AND 180::double precision
        AND coordinates[2] BETWEEN -90::double precision AND 90::double precision
    )
);
COMMENT ON TABLE map_points IS 'Точки на карте';
COMMENT ON COLUMN map_points.created_at IS 'Дата создания точки';
COMMENT ON COLUMN map_points.title IS 'Имя точки';
COMMENT ON COLUMN map_points.coordinates IS 'Координаты точки';
COMMENT ON COLUMN map_points.description IS 'Краткое описание точки';
COMMENT ON COLUMN map_points.flag_is_meeting IS 'Место встречи';
COMMENT ON COLUMN map_points.flag_has_socket IS 'Есть розетка';
COMMENT ON COLUMN map_points.flag_disabled IS 'Не показывать на сайте';

CREATE POLICY "Enable read access for all users" ON map_points FOR SELECT TO anon USING ((flag_disabled = false));

ALTER TABLE map_points ENABLE ROW LEVEL SECURITY;

CREATE INDEX map_points_flag_disabled_idx ON map_points (flag_disabled);
