-- Раздел «События»: групповые покатушки, мероприятия, обучение.
-- Расписание задаётся явным списком дат (map_event_dates): одна дата — разовое
-- событие, несколько — повторяющееся с произвольными датами/временем.
-- Старт/финиш — привязанная точка (FK) ИЛИ ручные координаты.

CREATE TYPE event_types AS ENUM (
    'group_ride',
    'event',
    'training'
);
COMMENT ON TYPE event_types IS 'Типы событий: групповая покатушка, мероприятие, обучение';

CREATE TABLE map_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    type event_types DEFAULT 'group_ride'::event_types NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    description text,
    photo_bucket text DEFAULT 'map-event-photos'::text NOT NULL,
    photo_path text,
    duration_minutes smallint,
    location_text text,
    start_coordinates double precision[],
    finish_coordinates double precision[],
    start_point_id bigint REFERENCES map_points(id) ON DELETE SET NULL,
    finish_point_id bigint REFERENCES map_points(id) ON DELETE SET NULL,
    flag_disabled boolean DEFAULT false NOT NULL,
    CONSTRAINT map_events_title_check CHECK ((char_length(trim(BOTH FROM title)) > 3) AND (char_length(trim(BOTH FROM title)) < 100)),
    CONSTRAINT map_events_duration_check CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    CONSTRAINT map_events_start_coordinates_check CHECK (
        start_coordinates IS NULL OR (
            array_length(start_coordinates, 1) = 2
            AND start_coordinates[1] BETWEEN -180::double precision AND 180::double precision
            AND start_coordinates[2] BETWEEN -90::double precision AND 90::double precision
        )
    ),
    CONSTRAINT map_events_finish_coordinates_check CHECK (
        finish_coordinates IS NULL OR (
            array_length(finish_coordinates, 1) = 2
            AND finish_coordinates[1] BETWEEN -180::double precision AND 180::double precision
            AND finish_coordinates[2] BETWEEN -90::double precision AND 90::double precision
        )
    )
);
COMMENT ON TABLE map_events IS 'События сообщества: покатушки, мероприятия, обучение';
COMMENT ON COLUMN map_events.type IS 'Тип события';
COMMENT ON COLUMN map_events.title IS 'Название события';
COMMENT ON COLUMN map_events.description IS 'Описание события';
COMMENT ON COLUMN map_events.photo_bucket IS 'Bucket в Supabase Storage с фотографией события';
COMMENT ON COLUMN map_events.photo_path IS 'Путь к фотографии события внутри bucket';
COMMENT ON COLUMN map_events.duration_minutes IS 'Длительность события в минутах';
COMMENT ON COLUMN map_events.location_text IS 'Человекочитаемое место («КБТУ»)';
COMMENT ON COLUMN map_events.start_coordinates IS 'Ручные координаты старта [lon, lat] (если точка не привязана)';
COMMENT ON COLUMN map_events.finish_coordinates IS 'Ручные координаты финиша [lon, lat] (если точка не привязана)';
COMMENT ON COLUMN map_events.start_point_id IS 'Точка-старт (FK map_points). Если задана — координаты берутся из точки.';
COMMENT ON COLUMN map_events.finish_point_id IS 'Точка-финиш (FK map_points). Если задана — координаты берутся из точки.';
COMMENT ON COLUMN map_events.flag_disabled IS 'Не показывать на сайте';

-- Явные даты события: одна или несколько.
CREATE TABLE map_event_dates (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_id bigint NOT NULL REFERENCES map_events(id) ON DELETE CASCADE,
    starts_at timestamp with time zone NOT NULL,
    note text,
    CONSTRAINT map_event_dates_event_id_starts_at_key UNIQUE (event_id, starts_at)
);
COMMENT ON TABLE map_event_dates IS 'Даты проведения события (одна — разовое, несколько — повторяющееся)';
COMMENT ON COLUMN map_event_dates.starts_at IS 'Дата-время конкретного вхождения';
COMMENT ON COLUMN map_event_dates.note IS 'Заметка к конкретной дате';

-- updated_at
CREATE OR REPLACE FUNCTION set_map_events_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;
CREATE TRIGGER set_map_events_updated_at_trigger
BEFORE UPDATE ON map_events
FOR EACH ROW
EXECUTE FUNCTION set_map_events_updated_at();

-- Анонимное чтение опубликованных событий и их дат
ALTER TABLE map_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON map_events
    FOR SELECT TO anon USING ((flag_disabled = false));

ALTER TABLE map_event_dates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON map_event_dates
    FOR SELECT
    TO anon
    USING (
        EXISTS (
            SELECT 1
            FROM map_events
            WHERE map_events.id = map_event_dates.event_id
                AND map_events.flag_disabled = false
        )
    );

CREATE INDEX map_events_flag_disabled_idx ON map_events (flag_disabled);
CREATE INDEX map_events_start_point_id_idx ON map_events (start_point_id);
CREATE INDEX map_events_finish_point_id_idx ON map_events (finish_point_id);
CREATE INDEX map_event_dates_event_id_starts_at_idx ON map_event_dates (event_id, starts_at);

-- Полный доступ администраторов
CREATE POLICY "Администраторы читают все события"
    ON map_events
    FOR SELECT TO authenticated
    USING (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));
CREATE POLICY "Администраторы создают события"
    ON map_events
    FOR INSERT TO authenticated
    WITH CHECK (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));
CREATE POLICY "Администраторы обновляют события"
    ON map_events
    FOR UPDATE TO authenticated
    USING (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()))
    WITH CHECK (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));
CREATE POLICY "Администраторы удаляют события"
    ON map_events
    FOR DELETE TO authenticated
    USING (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));

CREATE POLICY "Администраторы читают все даты событий"
    ON map_event_dates
    FOR SELECT TO authenticated
    USING (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));
CREATE POLICY "Администраторы создают даты событий"
    ON map_event_dates
    FOR INSERT TO authenticated
    WITH CHECK (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));
CREATE POLICY "Администраторы обновляют даты событий"
    ON map_event_dates
    FOR UPDATE TO authenticated
    USING (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()))
    WITH CHECK (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));
CREATE POLICY "Администраторы удаляют даты событий"
    ON map_event_dates
    FOR DELETE TO authenticated
    USING (EXISTS (SELECT 1 FROM map_admin_users m WHERE m.user_id = auth.uid()));
